spring:
  application:
    name: flightapp-backend

  datasource:
    url: jdbc:postgresql://172.26.219.217:5433/flightapp
    username: flightapp
    password: flightapp
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email

server:
  port: 8080

flightapp:
  storage:
    connection-string: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://172.26.219.217:10000/devstoreaccount1;"
    container-name: "flight-files"
  frontend:
    base-url: ${FRONTEND_BASE_URL:http://localhost:4200}