spring:
  application:
    name: flightapp-backend

  datasource:
    url: jdbc:postgresql://172.26.219.217:5433/flightapp
    username: flightapp
    password: flightapp
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email

server:
  port: 8080

flightapp:
  storage:
    connection-string: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFeqCnf2mpD7/9psL7++hX4wNslbtdMgRY9z5KJeOfhFz6MD+KQC6T4XQ8v9su1phcp2MA==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;"
    container-name: flight-files